const { test, expect } = require('@playwright/test');
test('Seam Labs round trip, compact middle and safe playback', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/src/labs/index.html');
  await page.getByRole('link', { name: 'Open Agent node', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Agent node · Session Lab', exact: true })).toBeVisible();
  const nodes = page.locator('.card-cell');
  await expect(nodes).toHaveCount(10);
  await expect(page.locator('.fixture-label,.fixture-flags,.state-group')).toHaveCount(0);
  await page.getByRole('radio', { name: 'middle', exact: true }).check();
  await expect(nodes.first().locator('[data-field="time"]')).toBeVisible();
  await expect(nodes.first().locator('.agent-card-pet')).toBeVisible();
  await expect(nodes.first().locator('[data-field="realm"],[data-field="team"],[data-field="model"]')).toHaveCount(0);
  expect(await nodes.first().locator('.agent-card-surface').evaluate(el => getComputedStyle(el).fillOpacity)).toBe('0.1');
  await page.getByRole('checkbox', { name: 'Animation on', exact: true }).uncheck();
  await expect(page.locator('animate')).toHaveCount(0);
  await page.getByRole('checkbox', { name: 'Animation on', exact: true }).check();
  await expect(nodes.first().locator('animate').first()).toBeAttached();
  await page.getByRole('combobox', { name: 'Hermes pet', exact: true }).selectOption('belayer-cat');
  await expect(nodes.first().locator('.agent-card-pet-pending')).toBeVisible();
  await expect(page.locator('.card-cell animate,.card-cell image')).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Hermes pet', exact: true }).selectOption('black-dragon-pet');
  await page.getByRole('radio', { name: 'near', exact: true }).check();
  await page.getByRole('combobox', { name: 'Node width', exact: true }).selectOption('280');
  await page.getByRole('combobox', { name: 'Attention override', exact: true }).selectOption('all-on');
  await page.getByRole('combobox', { name: 'Actor multiplicity override', exact: true }).selectOption('all-on');
  await expect(nodes.first().locator('[data-actor-layer]')).toHaveCount(3);
  await page.getByRole('link', { name: '← M3E Seam Labs', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'M3E Seam Labs', exact: true })).toBeVisible();
  await page.locator('a[href="/src/labs/node-draw/node-lab.html"]').click();
  await expect(page.locator('#sample')).toBeVisible();
  await page.getByRole('link', { name: '← M3E Seam Labs', exact: true }).click();
  await page.getByRole('link', { name: 'Open Agent node', exact: true }).click();
  expect(errors).toEqual([]);
});
