#!/usr/bin/env node

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), "..");

const defaultDocsDir = path.join(repoRoot, "docs");
const defaultOutput = path.join(defaultDocsDir, "_generated", "TheDesign.md");
const generatedDirName = "_generated";
const includedExtensions = new Set([".md", ".txt"]);

function usage() {
  return [
    "Usage: node scripts/concat-docs.mjs [--docs-dir <dir>] [--out <file>]",
    "",
    "Concatenates all .md and .txt files under docs/ into docs/_generated/TheDesign.md.",
    "The docs/_generated directory is excluded to avoid self-inclusion.",
  ].join("\n");
}

function parseArgs(argv) {
  const options = {
    docsDir: defaultDocsDir,
    output: defaultOutput,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--help" || arg === "-h") {
      console.log(usage());
      process.exit(0);
    }
    if (arg === "--docs-dir") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--docs-dir requires a path");
      }
      options.docsDir = path.resolve(repoRoot, value);
      index += 1;
      continue;
    }
    if (arg === "--out") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--out requires a path");
      }
      options.output = path.resolve(repoRoot, value);
      index += 1;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  return options;
}

function toPosix(relativePath) {
  return relativePath.split(path.sep).join("/");
}

function comparePath(a, b) {
  return a.localeCompare(b, "en", {
    numeric: true,
    sensitivity: "base",
  });
}

async function collectDocuments(rootDir, currentDir = rootDir) {
  const dirents = await readdir(currentDir, { withFileTypes: true });
  const files = [];

  for (const dirent of dirents) {
    const fullPath = path.join(currentDir, dirent.name);
    const relativePath = path.relative(rootDir, fullPath);
    const parts = relativePath.split(path.sep);

    if (parts.includes(generatedDirName)) {
      continue;
    }

    if (dirent.isDirectory()) {
      files.push(...(await collectDocuments(rootDir, fullPath)));
      continue;
    }

    if (!dirent.isFile()) {
      continue;
    }

    if (!includedExtensions.has(path.extname(dirent.name).toLowerCase())) {
      continue;
    }

    files.push({
      fullPath,
      relativePath: toPosix(relativePath),
    });
  }

  return files.sort((a, b) => comparePath(a.relativePath, b.relativePath));
}

function buildTableOfContents(documents) {
  const groups = new Map();

  for (const document of documents) {
    const dir = path.posix.dirname(document.relativePath);
    const group = dir === "." ? "/" : `${dir}/`;
    if (!groups.has(group)) {
      groups.set(group, []);
    }
    groups.get(group).push(path.posix.basename(document.relativePath));
  }

  const lines = ["## Table of Contents", ""];
  for (const [group, names] of groups.entries()) {
    lines.push(group === "/" ? "- **/** (root)" : `- **${group}**`);
    for (const name of names) {
      lines.push(`  - ${name}`);
    }
  }

  return lines.join("\n");
}

function normalizeContent(content) {
  return content.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trimEnd();
}

async function buildDocument(options) {
  const documents = await collectDocuments(options.docsDir);
  const generatedAt = new Date().toISOString().replace(/\.\d{3}Z$/, " UTC");
  const chunks = [
    "# TheDesign — docs 統合ドキュメント",
    "",
    `> Auto-generated by \`scripts/concat-docs.mjs\` on ${generatedAt}`,
    "",
    buildTableOfContents(documents),
  ];

  for (const document of documents) {
    const title = path.posix.basename(document.relativePath);
    const content = normalizeContent(await readFile(document.fullPath, "utf8"));
    chunks.push(
      "",
      "---",
      "",
      `### ${title}`,
      "",
      "```",
      `source: ${document.relativePath}`,
      "```",
      "",
      content,
    );
  }

  return {
    text: `${chunks.join("\n")}\n`,
    count: documents.length,
  };
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const result = await buildDocument(options);
  await mkdir(path.dirname(options.output), { recursive: true });
  await writeFile(options.output, result.text, "utf8");
  console.log(`Wrote ${path.relative(repoRoot, options.output)} (${result.count} documents)`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
