#!/usr/bin/env bash
# docs 内の .md / .txt ファイルを機械的に結合して TheDesign.md を生成する
# フォルダ構造 → 見出しレベルに変換
#   docs/             → (トップ)
#   docs/03_Spec/     → # 03_Spec
#   docs/03_Spec/sub/ → ## sub  (もしあれば)
# 各ファイルは ### ファイル名 の見出し付きで本文をそのまま挿入

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SRC="docs"
OUT="TheDesign.md"

: > "$OUT"   # 出力ファイルを空にする

echo "# TheDesign — docs 統合ドキュメント" >> "$OUT"
echo "" >> "$OUT"
echo "> Auto-generated by \`scripts/concat-docs.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUT"
echo "" >> "$OUT"

# --- TOC 生成 ---
echo "## Table of Contents" >> "$OUT"
echo "" >> "$OUT"

prev_dir=""
find "$SRC" -type f \( -name '*.md' -o -name '*.txt' \) \
  ! -path '*/.obsidian/*' \
  | LC_ALL=C sort | while IFS= read -r filepath; do

  relpath="${filepath#$SRC/}"
  dirpart="$(dirname "$relpath")"
  filename="$(basename "$relpath")"

  # ディレクトリが変わったら見出し表示
  if [[ "$dirpart" != "$prev_dir" ]]; then
    if [[ "$dirpart" == "." ]]; then
      echo "- **/** (root)" >> "$OUT"
    else
      echo "- **${dirpart}/**" >> "$OUT"
    fi
    prev_dir="$dirpart"
  fi
  echo "  - ${filename}" >> "$OUT"
done

echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "" >> "$OUT"

# --- 本文結合 ---
prev_dir=""
find "$SRC" -type f \( -name '*.md' -o -name '*.txt' \) \
  ! -path '*/.obsidian/*' \
  | LC_ALL=C sort | while IFS= read -r filepath; do

  relpath="${filepath#$SRC/}"
  dirpart="$(dirname "$relpath")"
  filename="$(basename "$relpath")"

  # ディレクトリが変わったらセクション見出し
  if [[ "$dirpart" != "$prev_dir" ]]; then
    depth=$(echo "$dirpart" | tr '/' '\n' | wc -l)
    if [[ "$dirpart" == "." ]]; then
      hashes="#"
      label="(root)"
    else
      # フォルダ深さに応じて # の数を決定 (1階層=##, 2階層=### ...)
      hashes=$(printf '#%.0s' $(seq 1 $((depth + 1))))
      label="$dirpart"
    fi
    echo "" >> "$OUT"
    echo "${hashes} ${label}" >> "$OUT"
    echo "" >> "$OUT"
    prev_dir="$dirpart"
  fi

  # ファイル見出し (フォルダ深さ + 1)
  if [[ "$dirpart" == "." ]]; then
    file_hashes="##"
  else
    depth=$(echo "$dirpart" | tr '/' '\n' | wc -l)
    file_hashes=$(printf '#%.0s' $(seq 1 $((depth + 2))))
  fi

  echo "${file_hashes} ${filename}" >> "$OUT"
  echo "" >> "$OUT"
  echo '```' >> "$OUT"
  echo "source: ${relpath}" >> "$OUT"
  echo '```' >> "$OUT"
  echo "" >> "$OUT"
  cat "$filepath" >> "$OUT"
  echo "" >> "$OUT"
  echo "---" >> "$OUT"
  echo "" >> "$OUT"

done

echo ""
echo "Done: $(wc -l < "$OUT") lines -> $OUT"
